/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as CustomerComplaintsRouteImport } from './routes/customer/complaints'
import { Route as CustomerBookingsRouteImport } from './routes/customer/bookings'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as CustomerRoomsIndexRouteImport } from './routes/customer/rooms/index'
import { Route as CustomerPaymentsIndexRouteImport } from './routes/customer/payments/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminRoomsIndexRouteImport } from './routes/admin/rooms/index'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices/index'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin/complaints/index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings/index'
import { Route as CustomerRoomsIdRouteImport } from './routes/customer/rooms/$id'
import { Route as CustomerPaymentsInvoiceIdRouteImport } from './routes/customer/payments/$invoiceId'
import { Route as CustomerBookingsNewRouteImport } from './routes/customer/bookings.new'
import { Route as CustomerBookingsIdRouteImport } from './routes/customer/bookings.$id'
import { Route as AdminSettingsSecurityRouteImport } from './routes/admin/settings/security'
import { Route as AdminRoomsNewRouteImport } from './routes/admin/rooms/new'
import { Route as AdminInvoicesIdRouteImport } from './routes/admin/invoices/$id'
import { Route as AdminComplaintsIdRouteImport } from './routes/admin/complaints/$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin/bookings/$id'
import { Route as AdminRoomsIdEditRouteImport } from './routes/admin/rooms/$id.edit'

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerComplaintsRoute = CustomerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerRoomsIndexRoute = CustomerRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentsIndexRoute = CustomerPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsIndexRoute = AdminRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerRoomsIdRoute = CustomerRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentsInvoiceIdRoute =
  CustomerPaymentsInvoiceIdRouteImport.update({
    id: '/payments/$invoiceId',
    path: '/payments/$invoiceId',
    getParentRoute: () => CustomerRoute,
  } as any)
const CustomerBookingsNewRoute = CustomerBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomerBookingsRoute,
} as any)
const CustomerBookingsIdRoute = CustomerBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerBookingsRoute,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsNewRoute = AdminRoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIdRoute = AdminInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsIdRoute = AdminComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsIdEditRoute = AdminRoomsIdEditRouteImport.update({
  id: '/rooms/$id/edit',
  path: '/rooms/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/payments/$invoiceId': typeof CustomerPaymentsInvoiceIdRoute
  '/customer/rooms/$id': typeof CustomerRoomsIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/customer/payments/': typeof CustomerPaymentsIndexRoute
  '/customer/rooms/': typeof CustomerRoomsIndexRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/payments/$invoiceId': typeof CustomerPaymentsInvoiceIdRoute
  '/customer/rooms/$id': typeof CustomerRoomsIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/rooms': typeof AdminRoomsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/customer/payments': typeof CustomerPaymentsIndexRoute
  '/customer/rooms': typeof CustomerRoomsIndexRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/payments/$invoiceId': typeof CustomerPaymentsInvoiceIdRoute
  '/customer/rooms/$id': typeof CustomerRoomsIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/rooms/': typeof AdminRoomsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/customer/payments/': typeof CustomerPaymentsIndexRoute
  '/customer/rooms/': typeof CustomerRoomsIndexRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/customer'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/auth/login'
    | '/auth/register'
    | '/customer/bookings'
    | '/customer/complaints'
    | '/customer/profile'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/complaints/$id'
    | '/admin/invoices/$id'
    | '/admin/rooms/new'
    | '/admin/settings/security'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/payments/$invoiceId'
    | '/customer/rooms/$id'
    | '/admin/bookings/'
    | '/admin/complaints/'
    | '/admin/invoices/'
    | '/admin/rooms/'
    | '/admin/settings/'
    | '/customer/payments/'
    | '/customer/rooms/'
    | '/admin/rooms/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/customer'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/auth/login'
    | '/auth/register'
    | '/customer/bookings'
    | '/customer/complaints'
    | '/customer/profile'
    | '/admin'
    | '/admin/bookings/$id'
    | '/admin/complaints/$id'
    | '/admin/invoices/$id'
    | '/admin/rooms/new'
    | '/admin/settings/security'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/payments/$invoiceId'
    | '/customer/rooms/$id'
    | '/admin/bookings'
    | '/admin/complaints'
    | '/admin/invoices'
    | '/admin/rooms'
    | '/admin/settings'
    | '/customer/payments'
    | '/customer/rooms'
    | '/admin/rooms/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/customer'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/auth/login'
    | '/auth/register'
    | '/customer/bookings'
    | '/customer/complaints'
    | '/customer/profile'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/complaints/$id'
    | '/admin/invoices/$id'
    | '/admin/rooms/new'
    | '/admin/settings/security'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/payments/$invoiceId'
    | '/customer/rooms/$id'
    | '/admin/bookings/'
    | '/admin/complaints/'
    | '/admin/invoices/'
    | '/admin/rooms/'
    | '/admin/settings/'
    | '/customer/payments/'
    | '/customer/rooms/'
    | '/admin/rooms/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/complaints': {
      id: '/customer/complaints'
      path: '/complaints'
      fullPath: '/customer/complaints'
      preLoaderRoute: typeof CustomerComplaintsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/rooms/': {
      id: '/customer/rooms/'
      path: '/rooms'
      fullPath: '/customer/rooms/'
      preLoaderRoute: typeof CustomerRoomsIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/payments/': {
      id: '/customer/payments/'
      path: '/payments'
      fullPath: '/customer/payments/'
      preLoaderRoute: typeof CustomerPaymentsIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms/': {
      id: '/admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminRoomsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/rooms/$id': {
      id: '/customer/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/customer/rooms/$id'
      preLoaderRoute: typeof CustomerRoomsIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/payments/$invoiceId': {
      id: '/customer/payments/$invoiceId'
      path: '/payments/$invoiceId'
      fullPath: '/customer/payments/$invoiceId'
      preLoaderRoute: typeof CustomerPaymentsInvoiceIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings/new': {
      id: '/customer/bookings/new'
      path: '/new'
      fullPath: '/customer/bookings/new'
      preLoaderRoute: typeof CustomerBookingsNewRouteImport
      parentRoute: typeof CustomerBookingsRoute
    }
    '/customer/bookings/$id': {
      id: '/customer/bookings/$id'
      path: '/$id'
      fullPath: '/customer/bookings/$id'
      preLoaderRoute: typeof CustomerBookingsIdRouteImport
      parentRoute: typeof CustomerBookingsRoute
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/settings/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms/new': {
      id: '/admin/rooms/new'
      path: '/rooms/new'
      fullPath: '/admin/rooms/new'
      preLoaderRoute: typeof AdminRoomsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/$id': {
      id: '/admin/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminInvoicesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints/$id': {
      id: '/admin/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AdminComplaintsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms/$id/edit': {
      id: '/admin/rooms/$id/edit'
      path: '/rooms/$id/edit'
      fullPath: '/admin/rooms/$id/edit'
      preLoaderRoute: typeof AdminRoomsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminComplaintsIdRoute: typeof AdminComplaintsIdRoute
  AdminInvoicesIdRoute: typeof AdminInvoicesIdRoute
  AdminRoomsNewRoute: typeof AdminRoomsNewRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminRoomsIndexRoute: typeof AdminRoomsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminRoomsIdEditRoute: typeof AdminRoomsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminComplaintsIdRoute: AdminComplaintsIdRoute,
  AdminInvoicesIdRoute: AdminInvoicesIdRoute,
  AdminRoomsNewRoute: AdminRoomsNewRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminRoomsIndexRoute: AdminRoomsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminRoomsIdEditRoute: AdminRoomsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerBookingsRouteChildren {
  CustomerBookingsIdRoute: typeof CustomerBookingsIdRoute
  CustomerBookingsNewRoute: typeof CustomerBookingsNewRoute
}

const CustomerBookingsRouteChildren: CustomerBookingsRouteChildren = {
  CustomerBookingsIdRoute: CustomerBookingsIdRoute,
  CustomerBookingsNewRoute: CustomerBookingsNewRoute,
}

const CustomerBookingsRouteWithChildren =
  CustomerBookingsRoute._addFileChildren(CustomerBookingsRouteChildren)

interface CustomerRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRouteWithChildren
  CustomerComplaintsRoute: typeof CustomerComplaintsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerPaymentsInvoiceIdRoute: typeof CustomerPaymentsInvoiceIdRoute
  CustomerRoomsIdRoute: typeof CustomerRoomsIdRoute
  CustomerPaymentsIndexRoute: typeof CustomerPaymentsIndexRoute
  CustomerRoomsIndexRoute: typeof CustomerRoomsIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRouteWithChildren,
  CustomerComplaintsRoute: CustomerComplaintsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerPaymentsInvoiceIdRoute: CustomerPaymentsInvoiceIdRoute,
  CustomerRoomsIdRoute: CustomerRoomsIdRoute,
  CustomerPaymentsIndexRoute: CustomerPaymentsIndexRoute,
  CustomerRoomsIndexRoute: CustomerRoomsIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
