/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRoomsRouteImport } from './routes/customer/rooms'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as CustomerPaymentsRouteImport } from './routes/customer/payments'
import { Route as CustomerComplaintsRouteImport } from './routes/customer/complaints'
import { Route as CustomerBookingsRouteImport } from './routes/customer/bookings'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminComplaintsRouteImport } from './routes/admin/complaints'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as CustomerRoomsIdRouteImport } from './routes/customer/rooms.$id'
import { Route as CustomerPaymentsInvoiceIdRouteImport } from './routes/customer/payments.$invoiceId'
import { Route as CustomerBookingsNewRouteImport } from './routes/customer/bookings.new'
import { Route as CustomerBookingsIdRouteImport } from './routes/customer/bookings.$id'
import { Route as AdminRoomsNewRouteImport } from './routes/admin/rooms.new'
import { Route as AdminComplaintsIdRouteImport } from './routes/admin/complaints.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin/bookings.$id'
import { Route as AdminRoomsIdEditRouteImport } from './routes/admin/rooms.$id.edit'

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoomsRoute = CustomerRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentsRoute = CustomerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerComplaintsRoute = CustomerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/admin/complaints',
  path: '/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoomsIdRoute = CustomerRoomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerRoomsRoute,
} as any)
const CustomerPaymentsInvoiceIdRoute =
  CustomerPaymentsInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => CustomerPaymentsRoute,
  } as any)
const CustomerBookingsNewRoute = CustomerBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomerBookingsRoute,
} as any)
const CustomerBookingsIdRoute = CustomerBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerBookingsRoute,
} as any)
const AdminRoomsNewRoute = AdminRoomsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoomsRoute,
} as any)
const AdminComplaintsIdRoute = AdminComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminComplaintsRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminRoomsIdEditRoute = AdminRoomsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminRoomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rooms': typeof AdminRoomsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/payments': typeof CustomerPaymentsRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/rooms': typeof CustomerRoomsRouteWithChildren
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/payments/$invoiceId': typeof CustomerPaymentsInvoiceIdRoute
  '/customer/rooms/$id': typeof CustomerRoomsIdRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rooms': typeof AdminRoomsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/payments': typeof CustomerPaymentsRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/rooms': typeof CustomerRoomsRouteWithChildren
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/payments/$invoiceId': typeof CustomerPaymentsInvoiceIdRoute
  '/customer/rooms/$id': typeof CustomerRoomsIdRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rooms': typeof AdminRoomsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/bookings': typeof CustomerBookingsRouteWithChildren
  '/customer/complaints': typeof CustomerComplaintsRoute
  '/customer/payments': typeof CustomerPaymentsRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/rooms': typeof CustomerRoomsRouteWithChildren
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/admin/rooms/new': typeof AdminRoomsNewRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/bookings/new': typeof CustomerBookingsNewRoute
  '/customer/payments/$invoiceId': typeof CustomerPaymentsInvoiceIdRoute
  '/customer/rooms/$id': typeof CustomerRoomsIdRoute
  '/admin/rooms/$id/edit': typeof AdminRoomsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/customer'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/customer/bookings'
    | '/customer/complaints'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/rooms'
    | '/admin/bookings/$id'
    | '/admin/complaints/$id'
    | '/admin/rooms/new'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/payments/$invoiceId'
    | '/customer/rooms/$id'
    | '/admin/rooms/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/customer'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/customer/bookings'
    | '/customer/complaints'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/rooms'
    | '/admin/bookings/$id'
    | '/admin/complaints/$id'
    | '/admin/rooms/new'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/payments/$invoiceId'
    | '/customer/rooms/$id'
    | '/admin/rooms/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/customer'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/payments'
    | '/admin/rooms'
    | '/auth/login'
    | '/auth/register'
    | '/customer/bookings'
    | '/customer/complaints'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/rooms'
    | '/admin/bookings/$id'
    | '/admin/complaints/$id'
    | '/admin/rooms/new'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/payments/$invoiceId'
    | '/customer/rooms/$id'
    | '/admin/rooms/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminComplaintsRoute: typeof AdminComplaintsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRoomsRoute: typeof AdminRoomsRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/rooms': {
      id: '/customer/rooms'
      path: '/rooms'
      fullPath: '/customer/rooms'
      preLoaderRoute: typeof CustomerRoomsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/payments': {
      id: '/customer/payments'
      path: '/payments'
      fullPath: '/customer/payments'
      preLoaderRoute: typeof CustomerPaymentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/complaints': {
      id: '/customer/complaints'
      path: '/complaints'
      fullPath: '/customer/complaints'
      preLoaderRoute: typeof CustomerComplaintsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/rooms/$id': {
      id: '/customer/rooms/$id'
      path: '/$id'
      fullPath: '/customer/rooms/$id'
      preLoaderRoute: typeof CustomerRoomsIdRouteImport
      parentRoute: typeof CustomerRoomsRoute
    }
    '/customer/payments/$invoiceId': {
      id: '/customer/payments/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/customer/payments/$invoiceId'
      preLoaderRoute: typeof CustomerPaymentsInvoiceIdRouteImport
      parentRoute: typeof CustomerPaymentsRoute
    }
    '/customer/bookings/new': {
      id: '/customer/bookings/new'
      path: '/new'
      fullPath: '/customer/bookings/new'
      preLoaderRoute: typeof CustomerBookingsNewRouteImport
      parentRoute: typeof CustomerBookingsRoute
    }
    '/customer/bookings/$id': {
      id: '/customer/bookings/$id'
      path: '/$id'
      fullPath: '/customer/bookings/$id'
      preLoaderRoute: typeof CustomerBookingsIdRouteImport
      parentRoute: typeof CustomerBookingsRoute
    }
    '/admin/rooms/new': {
      id: '/admin/rooms/new'
      path: '/new'
      fullPath: '/admin/rooms/new'
      preLoaderRoute: typeof AdminRoomsNewRouteImport
      parentRoute: typeof AdminRoomsRoute
    }
    '/admin/complaints/$id': {
      id: '/admin/complaints/$id'
      path: '/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AdminComplaintsIdRouteImport
      parentRoute: typeof AdminComplaintsRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/rooms/$id/edit': {
      id: '/admin/rooms/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/rooms/$id/edit'
      preLoaderRoute: typeof AdminRoomsIdEditRouteImport
      parentRoute: typeof AdminRoomsRoute
    }
  }
}

interface CustomerBookingsRouteChildren {
  CustomerBookingsIdRoute: typeof CustomerBookingsIdRoute
  CustomerBookingsNewRoute: typeof CustomerBookingsNewRoute
}

const CustomerBookingsRouteChildren: CustomerBookingsRouteChildren = {
  CustomerBookingsIdRoute: CustomerBookingsIdRoute,
  CustomerBookingsNewRoute: CustomerBookingsNewRoute,
}

const CustomerBookingsRouteWithChildren =
  CustomerBookingsRoute._addFileChildren(CustomerBookingsRouteChildren)

interface CustomerPaymentsRouteChildren {
  CustomerPaymentsInvoiceIdRoute: typeof CustomerPaymentsInvoiceIdRoute
}

const CustomerPaymentsRouteChildren: CustomerPaymentsRouteChildren = {
  CustomerPaymentsInvoiceIdRoute: CustomerPaymentsInvoiceIdRoute,
}

const CustomerPaymentsRouteWithChildren =
  CustomerPaymentsRoute._addFileChildren(CustomerPaymentsRouteChildren)

interface CustomerRoomsRouteChildren {
  CustomerRoomsIdRoute: typeof CustomerRoomsIdRoute
}

const CustomerRoomsRouteChildren: CustomerRoomsRouteChildren = {
  CustomerRoomsIdRoute: CustomerRoomsIdRoute,
}

const CustomerRoomsRouteWithChildren = CustomerRoomsRoute._addFileChildren(
  CustomerRoomsRouteChildren,
)

interface CustomerRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRouteWithChildren
  CustomerComplaintsRoute: typeof CustomerComplaintsRoute
  CustomerPaymentsRoute: typeof CustomerPaymentsRouteWithChildren
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerRoomsRoute: typeof CustomerRoomsRouteWithChildren
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRouteWithChildren,
  CustomerComplaintsRoute: CustomerComplaintsRoute,
  CustomerPaymentsRoute: CustomerPaymentsRouteWithChildren,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerRoomsRoute: CustomerRoomsRouteWithChildren,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface AdminBookingsRouteChildren {
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsIdRoute: AdminBookingsIdRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminComplaintsRouteChildren {
  AdminComplaintsIdRoute: typeof AdminComplaintsIdRoute
}

const AdminComplaintsRouteChildren: AdminComplaintsRouteChildren = {
  AdminComplaintsIdRoute: AdminComplaintsIdRoute,
}

const AdminComplaintsRouteWithChildren = AdminComplaintsRoute._addFileChildren(
  AdminComplaintsRouteChildren,
)

interface AdminRoomsRouteChildren {
  AdminRoomsNewRoute: typeof AdminRoomsNewRoute
  AdminRoomsIdEditRoute: typeof AdminRoomsIdEditRoute
}

const AdminRoomsRouteChildren: AdminRoomsRouteChildren = {
  AdminRoomsNewRoute: AdminRoomsNewRoute,
  AdminRoomsIdEditRoute: AdminRoomsIdEditRoute,
}

const AdminRoomsRouteWithChildren = AdminRoomsRoute._addFileChildren(
  AdminRoomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomerRoute: CustomerRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminComplaintsRoute: AdminComplaintsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRoomsRoute: AdminRoomsRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
