import type { Room } from '../types/room.types'

export const mockRooms: Room[] = [
  {
    id: '1',
    name: 'Standard Room with City View',
    type: 'standard',
    price: 150,
    description: 'Comfortable standard room with a beautiful view of the city. Perfect for business travelers and tourists alike.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Desk', 'Private Bathroom'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800',
    ],
    capacity: 2,
    available: true,
  },
  {
    id: '2',
    name: 'Deluxe Ocean View Suite',
    type: 'deluxe',
    price: 280,
    description: 'Spacious deluxe room with stunning ocean views. Features premium amenities and extra space for relaxation.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Ocean View', 'King Bed', 'Bathtub'],
    images: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
    ],
    capacity: 3,
    available: true,
  },
  {
    id: '3',
    name: 'Executive Suite',
    type: 'suite',
    price: 450,
    description: 'Luxurious suite with separate living area, bedroom, and premium amenities. Perfect for special occasions.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Living Room', 'King Bed', 'Bathtub', 'Room Service', 'Balcony'],
    images: [
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800',
    ],
    capacity: 4,
    available: true,
  },
  {
    id: '4',
    name: 'Garden View Standard Room',
    type: 'standard',
    price: 130,
    description: 'Peaceful standard room overlooking our beautiful gardens. A quiet retreat for nature lovers.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Garden View', 'Queen Bed', 'Private Bathroom'],
    images: [
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800',
    ],
    capacity: 2,
    available: true,
  },
  {
    id: '5',
    name: 'Deluxe Pool Access Room',
    type: 'deluxe',
    price: 320,
    description: 'Premium deluxe room with direct access to our swimming pool. Enjoy resort-style living.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Pool Access', 'Mini Bar', 'King Bed', 'Bathtub', 'Sun Deck'],
    images: [
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
    ],
    capacity: 3,
    available: false,
  },
  {
    id: '6',
    name: 'Presidential Penthouse',
    type: 'penthouse',
    price: 1200,
    description: 'The ultimate luxury experience. Stunning penthouse with panoramic views, private terrace, and VIP amenities.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Living Room', 'Dining Area', 'King Bed', 'Jacuzzi', 'Private Terrace', 'Panoramic View', 'Butler Service', 'Room Service'],
    images: [
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    capacity: 6,
    available: true,
  },
  {
    id: '7',
    name: 'Family Suite',
    type: 'suite',
    price: 380,
    description: 'Spacious suite designed for families. Two bedrooms, living area, and kid-friendly amenities.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Living Room', 'Two Bedrooms', 'Kitchenette', 'Bathtub'],
    images: [
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800',
    ],
    capacity: 5,
    available: true,
  },
  {
    id: '8',
    name: 'Business Deluxe Room',
    type: 'deluxe',
    price: 260,
    description: 'Designed for business travelers with workspace, ergonomic chair, and meeting facilities.',
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Work Desk', 'Ergonomic Chair', 'Mini Bar', 'King Bed'],
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    ],
    capacity: 2,
    available: true,
  },
]
